frc-862/nautilus

src/main/java/frc/robot/Constants.java
src/main/java/frc/robot/RobotContainer.java
src/main/java/frc/robot/subsystems/PhotonVision.java

8 vision sim

---

src/main/java/frc/robot/commands/TestAutoAlign.java

[#12] -  implement tx based auto align for photonvision

---

simgui-ds.json
src/main/java/frc/robot/Constants.java
src/main/java/frc/robot/RobotContainer.java
src/main/java/frc/robot/subsystems/PhotonVision.java
src/main/java/frc/robot/subsystems/Swerve.java

6 photonlib

---

src/main/java/frc/robot/Constants.java
src/main/java/frc/robot/subsystems/Elevator.java

created a base elevator subsystem with motor set up and basic methods

15 create base elevator subsystem

---

src/main/java/frc/robot/Constants.java
src/main/java/frc/robot/subsystems/Elevator.java
src/main/java/frc/robot/subsystems/Wrist.java

Created the wrist base subsystem

16 create base wrist subsystem

---

simgui-ds.json
src/main/java/frc/robot/Constants.java
src/main/java/frc/robot/RobotContainer.java
src/main/java/frc/robot/subsystems/Elevator.java
src/main/java/frc/robot/subsystems/Swerve.java

Elevator is fully simulated, it's not QUITE accurate to the robot, and it still  needs to be tuned, but I'll put the things into main in their current state so people work with a semi up-to-date elevator subsystem.
please do not close the branch after it's merged in.

17 elevator sim

---

src/main/java/frc/robot/Constants.java
src/main/java/frc/robot/subsystems/Elevator.java
src/main/java/frc/robot/subsystems/FishingRod.java
src/main/java/frc/robot/subsystems/Wrist.java

Created a Fishing Rod state system that includes the Wrist and Elevator subsystems.

14 create lift state system

---

src/main/java/frc/robot/Constants.java
src/main/java/frc/robot/subsystems/Elevator.java

[#28] canrange implementation and sim

---

src/main/java/frc/robot/subsystems/Wrist.java

Added Documentation to the Wrist subsystem

30 add documentation the wrist subsystem

---

src/main/java/frc/robot/Constants.java

40 create approximate coral placement map

---

src/main/java/frc/robot/commands/StandinCommands.java

Branch was already merged but I added on commands for FishingRod states

[#9] - implemented standin commands for states enum

---

src/main/java/frc/robot/Constants.java
src/main/java/frc/robot/RobotContainer.java
src/main/java/frc/robot/subsystems/LEDs.java

{#43] Added LEDs To Standin Commands.

---

src/main/java/frc/robot/RobotContainer.java

[#50] add button binding

---

src/main/java/frc/robot/RobotContainer.java
src/main/java/frc/robot/RobotMotors.java
src/main/java/frc/robot/subsystems/Wrist.java
src/test/java/frc/robot/ConstantsTest.java
src/test/java/frc/robot/subsystems/WristTest.java

[#64] Created example test for wrist

---

src/main/java/frc/robot/Constants.java

[#68] Added ButtonBox Constants

---

build.gradle

[#58] update version

---

src/main/java/frc/robot/Constants.java
src/main/java/frc/robot/subsystems/Collector.java

[#83] - created basic collector and constants

---

src/test/java/frc/robot/subsystems/ElevatorTest.java

[#106] Just set power and expected value to 0

---

src/main/java/frc/robot/Constants.java
src/main/java/frc/robot/RobotContainer.java

111 inconsistent use of tunerconstants in code

---

src/main/java/frc/robot/subsystems/PhotonVision.java
src/main/java/frc/robot/subsystems/Swerve.java

[#120] Cleanup photonvision + fix simulation

---

.github/workflows/gradle.yml
.github/workflows/simulate.yml

[#119] on push

---

src/main/java/frc/robot/Constants.java

[#116] Added a class at the top of constants for encoder offset values

---

src/main/java/frc/robot/RobotContainer.java

[#123] Just swapped button maps to triggers

---

src/main/deploy/elastic/test.json
src/main/java/frc/robot/Robot.java

We're gonna continue with elastic dashboard for the 2025 season due to wpilib implementation and our new capability of adding dashboard layouts
closes #65

[#65] added a way to create layouts for elastic

---

src/test/java/frc/robot/subsystems/CollectorTest.java

[#87] Created some collector unit tests

---

src/main/java/frc/robot/subsystems/Swerve.java

[#135] - fixed addvisionmeasurements to have standard devs setup

---

src/main/java/frc/robot/Robot.java

[#133] Change diabledPeriodic to disabledInit

---

src/test/java/frc/robot/subsystems/CollectorTest.java
src/test/java/frc/robot/subsystems/ElevatorTest.java
src/test/java/frc/robot/subsystems/WristTest.java

[#140] made the unit test files consistent and organized

---

src/main/java/frc/robot/Constants.java
src/main/java/frc/robot/RobotContainer.java
src/main/java/frc/robot/subsystems/Climber.java
src/test/java/frc/robot/subsystems/ClimberTest.java

139 create climb subsystem

---

src/main/java/frc/robot/subsystems/PhotonVision.java

[#149] - no more console filling

---

src/main/java/frc/robot/subsystems/PhotonVision.java

Closes #131 
i accidently pressed enter before finishing the name whoops it is what it is

[#131] - added pipeline switching and logging

---

src/test/java/frc/robot/subsystems/CoralCollectorTest.java

[#154] Commented out testSetPower

---

src/test/java/frc/robot/subsystems/ElevatorTest.java

[#156] Created the set position test

---

src/main/java/frc/robot/Constants.java
src/main/java/frc/robot/RobotContainer.java
src/main/java/frc/robot/subsystems/Swerve.java

157 slow mode and robot centric same time

---

src/main/java/frc/robot/Constants.java
src/main/java/frc/robot/subsystems/PhotonVision.java
src/main/java/frc/robot/subsystems/Swerve.java

closes [#161]
had to change swerve.java to factor in the stddevs for vision it should work but we do need to manually find the stddevs

161 implement confidence tuning for kalman filter

---

src/main/java/frc/robot/RobotContainer.java

[#169] - got rid of the broken button binding

---

src/main/java/frc/robot/Constants.java

[#173] Made the 13.5 values 11

---

src/main/java/frc/robot/Constants.java

[#176] update led length

---

src/main/java/frc/robot/RobotContainer.java

[#185] Added deadline for the rumble commands

---

.github/run_sim_timeout.sh
src/main/java/frc/robot/subsystems/Swerve.java

Please when merging squash the commits (many useless ones)
Commented out the shuffleboard value due to simulator errors
closes #184

184 sometimes simulator fails on GitHub

---

src/main/java/frc/robot/Constants.java
src/main/java/frc/robot/RobotContainer.java
src/main/java/frc/robot/subsystems/LEDs.java

closes #189
Approve the Thunder PR first pls!

[#189] thunderbolt implementation

---

src/main/java/frc/robot/RobotContainer.java

[#195] - made the multipliers apply in robotcontainer

---

src/main/java/frc/robot/Constants.java
src/main/java/frc/robot/RobotContainer.java
src/main/java/frc/robot/subsystems/LEDs.java

199 multistrip leds

---

src/main/java/frc/robot/subsystems/PhotonVision.java

[#200] made switch case to change origin based off of alliance

---

simgui-ds.json
src/main/java/frc/robot/Constants.java
src/main/java/frc/robot/RobotContainer.java
src/main/java/frc/robot/commands/CollectCoral.java
src/main/java/frc/robot/subsystems/LEDs.java
src/main/java/frc/robot/subsystems/PhotonVision.java
src/main/java/frc/robot/subsystems/Swerve.java

[#211] cleaned up ledstates and updated colors

---

src/main/java/frc/robot/RobotContainer.java

[#229] - Cleaned up Algae Control

---

src/main/java/frc/robot/RobotContainer.java

[#232] added Davids antitip

---

src/main/java/frc/robot/RobotContainer.java

[#240] - no more null exception for algae collector
